"""Initial migration

Revision ID: c9c4e216194e
Revises: 
Create Date: 2026-05-19 11:49:59.158052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c4e216194e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable_entries', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable_entries', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=160),
               nullable=True)

    # ### end Alembic commands ###
